services:
  web:
    image: gleidsonrocha/engaja-app:latest
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.web.loadbalancer.server.port=80"
    environment:
      APP_URL: "https://newsletter.engajacomunicacao.com.br"
      APP_CRYPT_KEY: ""
      DB_HOST: ""
      DB_PORT: 3306
      DB_NAME: ""
      DB_USER: ""
      DB_PASS: ""
      TZ: America/Fortaleza
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USER: monitoramento@engajacomunicacao.com.br
      MAIL_PASS: ""
      MAIL_FROM_EMAIL: monitoramento@engajacomunicacao.com.br
      MAIL_FROM_NAME: "Engaja Comunicação"
    volumes:
      - engaja_uploads:/var/www/html/public/uploads
    restart: unless-stopped

  scheduler:
    image: gleidsonrocha/engaja-app:latest
    environment:
      DB_HOST: ""
      DB_PORT: 3306
      DB_NAME: ""
      DB_USER: ""
      DB_PASS: ""
      TZ: America/Fortaleza
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USER: monitoramento@engajacomunicacao.com.br
      MAIL_PASS: ""
      MAIL_FROM_EMAIL: monitoramento@engajacomunicacao.com.br
      MAIL_FROM_NAME: "Engaja Comunicação"
    volumes:
      - engaja_uploads:/var/www/html/public/uploads
    restart: unless-stopped
    command: >
      sh -lc "mkdir -p /var/www/html/storage &&
              touch /var/www/html/storage/cron.log &&
              while true; do
                php /var/www/html/cron/send_scheduled.php >> /var/www/html/storage/cron.log 2>&1;
                sleep 60;
              done"

volumes:
  engaja_uploads:
